{
  "formatVersion": "1.1",
  "component": {
    "group": "com.futureworkshops.mobileworkflow",
    "module": "web",
    "version": "1.0.17-test",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "7khgin5dofhgne2b6a76blnmse"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        }
      ],
      "files": [
        {
          "name": "web-1.0.17-test.aar",
          "url": "web-1.0.17-test.aar",
          "size": 56841,
          "sha512": "1eb846856df30e8c4458d1400d9bb6fbc0207298f27077bcad7aaf4baf1426c0eb7b1a18c2e6a5ca55ec7a9b3ad64e8a14ff178238e1ba2d01b3061d18c53f9a",
          "sha256": "6c87cb3d9b832682dd15548408ad86bd9faabc3adebc7ddaff7056edbd436a0d",
          "sha1": "d81f19bfd5357d86ae1b1435080409c55c5f8cbd",
          "md5": "a5925f117f20ff1dc0f3fd5dcffb9e9e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "4.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.4"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxkotlin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.futureworkshops.mobileworkflow",
          "module": "mw-core",
          "version": {
            "requires": "1.0.17-test"
          }
        }
      ],
      "files": [
        {
          "name": "web-1.0.17-test.aar",
          "url": "web-1.0.17-test.aar",
          "size": 56841,
          "sha512": "1eb846856df30e8c4458d1400d9bb6fbc0207298f27077bcad7aaf4baf1426c0eb7b1a18c2e6a5ca55ec7a9b3ad64e8a14ff178238e1ba2d01b3061d18c53f9a",
          "sha256": "6c87cb3d9b832682dd15548408ad86bd9faabc3adebc7ddaff7056edbd436a0d",
          "sha1": "d81f19bfd5357d86ae1b1435080409c55c5f8cbd",
          "md5": "a5925f117f20ff1dc0f3fd5dcffb9e9e"
        }
      ]
    }
  ]
}
